### ISSUE TITLE
NullReferenceException in analyser UseInModifierForReadOnlyStructAnalyzer

### ISSUE THREAD

**Issue by meziantou** [SergeyTeplyakov/ErrorProne.NET#62]
````
Warning	AD0001	Analyzer 'ErrorProne.NET.Structs.UseInModifierForReadOnlyStructAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	

Analyzer 'ErrorProne.NET.Structs.UseInModifierForReadOnlyStructAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: ***
ISymbol: AddOrReplace (Method)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ErrorProne.NET.Core.StructSizeCalculator.TryGetPrimitiveSize(ITypeSymbol type, Int32& size, Int32& largestFieldSize)
   at ErrorProne.NET.Core.StructSizeCalculator.GetSize(SemanticModel semanticModel, ITypeSymbol type, Int32& capacity, Int32& largestFieldSize, Int32& actualSize)
   at ErrorProne.NET.Core.StructSizeCalculator.GetSize(SemanticModel semanticModel, ITypeSymbol type, Int32& capacity, Int32& largestFieldSize, Int32& actualSize)
   at ErrorProne.NET.Core.StructSizeCalculator.<>c__DisplayClass1_0.<ComputeStructSize>b__0(ITypeSymbol t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ErrorProne.NET.Core.StructSizeCalculator.ComputeStructSize(ITypeSymbol type, SemanticModel semanticModel)
   at ErrorProne.NET.Structs.UseInModifierForReadOnlyStructAnalyzer.WarnIfParameterIsReadOnly(SemanticModel model, IParameterSymbol p, Action`1 diagnosticReporter)
   at ErrorProne.NET.Structs.UseInModifierForReadOnlyStructAnalyzer.AnalyzeMethod(SymbolAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__38_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

````

**Comment by SergeyTeplyakov** [comment]
Thanks. Should be fixed now. Will publish a new version with the fix in a day or two.

**Comment by SergeyTeplyakov** [comment]
Closing the issue. The new package was published awhile ago already.
