### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by SergeyTeplyakov** [SergeyTeplyakov/ErrorProne.NET#91]
Code:
```csharp
using System;

namespace ConsoleApp11Core
{
    class Program
    {
struct LargeStruct
{
    private readonly long l1, l2, l3;
    public int Foo() => 42;
}

static void FooBar(in System.ReadOnlyMemory<int> mi)
{
    Console.WriteLine(mi.Pin().ToString());
}
static void ShouldWarn(in LargeStruct ls)
{ }

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}

```

Warning in VS:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'ErrorProne.NET.StructAnalyzers.NonReadOnlyStructPassedAsInParameterAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.	ConsoleApp11Core		1	Active	Analyzer 'ErrorProne.NET.StructAnalyzers.NonReadOnlyStructPassedAsInParameterAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: ConsoleApp11Core
ISymbol: ShouldWarn (Method)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ErrorProne.NET.StructAnalyzers.NonReadOnlyStructPassedAsInParameterAnalyzer.AnalyzeMethodSymbol(IMethodSymbol method, Action`1 reporter)
   at ErrorProne.NET.StructAnalyzers.NonReadOnlyStructPassedAsInParameterAnalyzer.AnalyzeMethod(SymbolAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__39_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

**Comment by SergeyTeplyakov** [comment]
Clarification: the analyzer fails on a partially correct code:

```csharp
static void ShouldWarn(in LargeStruct )
        { }
```

I.e. when the parameter is missing.
